// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import MyModalController from "./my_modal_controller"
application.register("my-modal", MyModalController)

import MyLoadingController from "./my_loading_controller"
application.register("my-loading", MyLoadingController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import Select2Controller from "./select2_controller"
application.register("select2", Select2Controller)